# Builds Python wheels for Pgenlib

# At this time, builds only on macOS aarch64
# because of problems with symlinks and the 
# dockerized cibuildwheel Linux build

name: Build Python Wheel

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 emulation
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: './2.0/Python'
        env:
          CIBW_ARCHS_LINUX: auto aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
