# Test python build on macOS aarch64

name: Run python build for Pgenlib on Apple Silicon

on: [push, pull_request]

jobs:
  run_build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-14 ]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run build
      working-directory: ./2.0/Python
      run: |
        python -m pip install pipx
        pipx run build
